//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_for_Claimy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Country_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Country_List()
        {
            this.tbl_Claimy_Employee = new HashSet<tbl_Claimy_Employee>();
            this.tbl_Customer = new HashSet<tbl_Customer>();
            this.tbl_Parking_Company = new HashSet<tbl_Parking_Company>();
        }
    
        public int fld_Number { get; set; }
        public string fld_Country { get; set; }
        public string fld_ZipCode { get; set; }
        public string fld_City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Claimy_Employee> tbl_Claimy_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Customer> tbl_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Parking_Company> tbl_Parking_Company { get; set; }
    }
}
