//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_for_Claimy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ticket_Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ticket_Case()
        {
            this.tbl_Image = new HashSet<tbl_Image>();
        }
    
        public string fld_Case_Ticket_ID { get; set; }
        public string fld_ParkingFine_Reason { get; set; }
        public string fld_Precedens { get; set; }
        public string fld_Status { get; set; }
        public string fld_Law_Violation { get; set; }
        public string fld_tax_number { get; set; }
        public Nullable<System.DateTime> fld_date_time { get; set; }
        public string fld_car_reg_no { get; set; }
        public Nullable<int> fld_parkingspace_id { get; set; }
        public Nullable<int> fld_traffic_warden_no { get; set; }
        public string fld_amount { get; set; }
        public string fld_payment_info { get; set; }
        public string fld_car_brand { get; set; }
        public string fld_CVRNumber { get; set; }
        public string fld_Customer_Email { get; set; }
        public string fld_EMP_ID { get; set; }
    
        public virtual tbl_Claimy_Employee tbl_Claimy_Employee { get; set; }
        public virtual tbl_Customer tbl_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Image> tbl_Image { get; set; }
        public virtual tbl_Parking_Company tbl_Parking_Company { get; set; }
    }
}
