//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_for_Claimy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Parking_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Parking_Company()
        {
            this.tbl_Ticket_Case = new HashSet<tbl_Ticket_Case>();
        }
    
        public string fld_CVRNR { get; set; }
        public string fld_Name { get; set; }
        public string fld_Adress { get; set; }
        public string fld_Email { get; set; }
        public string fld_Phone_No { get; set; }
        public string fld_Contact_Person { get; set; }
        public Nullable<int> fld_Country_Number { get; set; }
    
        public virtual tbl_Country_List tbl_Country_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ticket_Case> tbl_Ticket_Case { get; set; }
    }
}
