//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Application_for_Claimy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Image
    {
        public int fld_Image_ID { get; set; }
        public byte[] fld_image { get; set; }
        public string fld_Ticket_ID { get; set; }
    
        public virtual tbl_Ticket_Case tbl_Ticket_Case { get; set; }
    }
}
